# боковое меню настраивается в /includes/sidebar.html с шаблонированием по productCategories и solutionCategories
# Site settings
title: Proxia
subtitle: IoT solutions & devices
email: sale@proxia.ru
description: Proxia IoT platform, solutions & devices
baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://jumpgh.github.io" # the base hostname & protocol for your site
author:
street_address: Лесная д.5, офис 101
city: Жуковский
state: Московская область
zip_code: 140180
country: Россия
phone:  +7 (495) 204-60-10

# Social settings
socials:
  instagram: https://www.instagram.com/sprutm/
  twitter: https://twitter.com/ProgtechLPWAN
  vk: https://vk.com/sprutm

collections:
  products:
    output: true
  solutions:
    output: true

# категории устройств, устройства могут входить в несколько категорий одновременно
# ключ категории должен быть уникален, т.к. используется для html якорей
# детали по устройству лежат в _products
productCategories:
  controllers:
    name: Контроллеры
    description: Универсальный сетевой контроллер используется в качестве УСПД для сбора и обработки информации, а также управления различными исполнительными устройствами в системах АСКУЭ, а также в системах «умного дома».
  modules:
    name: Модули для контроллеров
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  sensors:
    name: Датчики
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  lorawan:
    name: Оборудование LoRaWAN
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  NB-IoT:
    name: Оборудование NB-IoT
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  relays:
    name: Реле
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  counters:
    name: Счетчики импульсов
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  asuno:
    name: АСУНО
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  accessories:
    name: Комплектующие
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.

# категории решений
# ключ категории должен быть уникален, т.к. используется для html якорей
# детали по рещению лежат в _solutions
solutionCategories:
  energy:
    name: Энергоменеджмент
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  smart:
    name: Умные здания
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  light:
    name: Управление освещением
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.


# Build settings
markdown: kramdown
