# боковое меню настраивается в /includes/sidebar.html с шаблонированием по productCategories и solutionCategories
# Site settings
title: Proxia
subtitle: IoT platform, solutions & devices
email: info@proxia.ru
description: Proxia IoT platform, solutions & devices
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Лесная д.5, офис 101
city: Жуковский
state: Московская область
zip_code: 140180
country: Россия
phone:  +7 (495) 204-60-10

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/jumpgh/editorial-jekyll-theme
gitlab_url: https://gitlab.com/
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com/
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

collections:
  products:
    output: true
  solutions:
    output: true

# категории устройств, устройства могут входить в несколько категорий одновременно
# ключ категории должен быть уникален, т.к. используется для html якорей
# детали по устройству лежат в _products
productCategories:
  controllers:
    name: Контроллеры
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  sensors:
    name: Датчики
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  lorawan:
    name: LoRaWAN
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  relay:
    name: Реле
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.

# категории решений
# ключ категории должен быть уникален, т.к. используется для html якорей
# детали по рещению лежат в _solutions
solutionCategories:
  energy:
    name: Энергоменеджмент
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  smart:
    name: Умные здания
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.
  light:
    name: Управление освещением
    description: enean ornare velit lacus, ac varius enim ullamcorper eu. Proin aliquam facilisis ante interdum congue. Integer mollis, nisl amet convallis, porttitor magna ullamcorper, amet egestas mauris. Ut magna finibus nisi nec lacinia. Nam maximus erat id euismod egestas. Pellentesque sapien ac quam. Lorem ipsum dolor sit nullam.


# Build settings
markdown: kramdown
